# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MWJkZWQ2YjU4MzRhYTllNGIwZGY2YWFkZGM1YWE5MjEyNmQxYjcyZGY1NjU2NjhhYWUzZjk1ZmYyMjNhODlkZTliM2Y0Y2Y5ZjBlMzZhMTczZjY5MmI4MDI1ZDExM2EyNDdhZGE1NGUxZGNjODY5NWUyZDMzNzRkNmVmZWJjZmI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
